default: &default
  adapter: postgresql
  encoding: unicode
  username: denver932

development:
  <<: *default
  database: Bookstore_development

test:
  <<: *default
  database: Bookstore_test

production:
  <<: *default
  database: Bookstore_production

